apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default2
spec:
  clusterResourceWhitelist: []
  destinations:
  - namespace: 'argocd-gitops'
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - https://github.com/blokje/gitops-template.git