apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-gitops
spec:
  destination:
    namespace: argocd-gitops
    server: https://kubernetes.default.svc
  source:
    path: platform/argocd-gitops/overlays/development
    repoURL: https://github.com/blokje/gitops-template.git
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
