apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-gitops
spec:
  destination:
    namespace: argocd-gitops
    server: https://kubernetes.default.svc
  source:
    path: argocd-config/gitops
    repoURL: https://github.com/blokje/gitops-template.git
    targetRevision: main
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
